# Generated by Django 5.1.2 on 2024-10-24 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictedFinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_symbol", models.CharField(max_length=10)),
                ("date", models.DateField()),
                (
                    "predicted_close_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["stock_symbol", "date"],
                        name="stockapp_pr_stock_s_1f2b03_idx",
                    )
                ],
                "unique_together": {("stock_symbol", "date")},
            },
        ),
    ]
